version: "2"

run:
  timeout: 8m
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  default: all
  disable:
    - exhaustruct
  settings:
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: snake
        overrides:
          - pkg: learning/k8s/example1/pkg/apis/samplecontroller/v1alpha1
            use-field-name: false
            rules:
              json: camel
          - pkg: learning/k8s/example3/pkg/apis/solarsystem/v1
            use-field-name: false
            rules:
              json: camel
    varnamelen:
      ignore-names:
        - ok
        - j
        - tt
        - ip
        - fd
      ignore-decls:
        - i int
        - m int
        - n int
        - wg sync.WaitGroup
        - wg *sync.WaitGroup
    revive:
      rules:
        - name: package-comments
          disabled: true
    funlen:
      lines: 100
    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120