on:
  push:
    branches:
      - master
name: Lint
jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.24.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout 20m
          version: v2.0.2
